# Generated by Django 2.1.3 on 2018-12-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prevData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_one', models.IntegerField()),
                ('input_two', models.IntegerField()),
            ],
        ),
    ]
